
title: Prompt Boost Blog
email: waqas.jamil47@gmail.com
description: >- 
  A blog about boosting AI productivity with GitHub Copilot and VS Code.
baseurl: ""
url: "https://wjamilaion.github.io"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives

paginate: 5
paginate_path: /page:num/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
